# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
target 'JZTCustomWidget' do
#    use_frameworks!
#    inhibit_all_warnings!
  pod 'Masonry'
  pod 'JZTCustomWidget'
  # Pods for JZTCustomWidget

end
